# Generated by Django 3.2.9 on 2022-01-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0010_alter_prize_id_alter_winner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='heart',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
