# Generated by Django 3.2.9 on 2022-01-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0011_prize_heart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='heart',
            field=models.IntegerField(default=0),
        ),
    ]
