# Generated by Django 2.1.7 on 2021-12-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='way',
            options={},
        ),
        migrations.AlterField(
            model_name='person',
            name='way_id',
            field=models.CharField(choices=[('Home', '宅配'),('Store', '店取')], default='Store', max_length=5),
        ),
    ]
