# Generated by Django 4.0 on 2021-12-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_delete_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
