# Generated by Django 4.0 on 2021-12-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='way_id',
            field=models.CharField(choices=[('Store', '店取'), ('Home', '宅配')], default='Store', max_length=5),
        ),
    ]
